spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: tolkien23
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        formart-sql: true
      database: postgresql
      database-plataform: org.hibernate.dialect.PostgreSQLDialect